export const siteMetadata = {
  title: 'Javascript Cheatsheet',
  description:
    'Anyone can forget how to make character classes for a regex, slice a list or do a for loop. This cheat sheet tries to provide a basic reference for beginner and advanced developers, lower the entry barrier for newcomers and help veterans refresh the old tricks.',
  keywords: [
    'javascript',
    'cheatsheet',
    'cheat',
    'sheet',
    'functions',
    'args',
    'kwargs',
    'sets',
    'dictionary',
    'list',
    'string',
    'regular',
    'expression',
    'formatting',
    'file',
    'path',
    'json',
    'test',
    'vscode',
    'comprehension',
    'exception',
    'debugging',
    'dataclasses',
    'environments',
    'flow control',
    'itertools',
  ],
  baseUrl: import.meta.env.VITE_BASE_URL || 'localhost:3000',
}
